'use strict';

const QUIZ_WIDGET_URI = 'ui://ez-quiz/quiz-v2.html';
const QUIZ_WIDGET_MIME_TYPE = 'text/html;profile=mcp-app';

function quizWidgetHtml() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <style>
    :root{color-scheme:light dark;--panel:#fff;--panel-2:#f1f3f7;--field:#f7f8fa;--text:#1d2027;--muted:#68707d;--border:#dce0e7;--border-strong:#c9ced8;--accent:#3478f6;--accent-press:#2867d8;--purple:#7133d4;--yellow:#ffc94a;--success:#18a566;--danger:#c43b4d;--focus:rgba(52,120,246,.25);--shadow:0 8px 26px rgba(25,31,45,.10);--radius-card:16px;--radius-control:12px}
    *{box-sizing:border-box}html,body{width:100%;min-height:100%;margin:0}body{padding:10px 12px 14px;font:15px/1.45 system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;color:var(--text);background:transparent;-webkit-text-size-adjust:100%}
    button,input,select{font:inherit}.app{width:100%;max-width:680px;margin:0 auto;border:1px solid var(--border);border-radius:var(--radius-card);background:var(--panel);overflow:hidden;box-shadow:var(--shadow)}
    .brandbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 14px;background:linear-gradient(120deg,#1d1d22,#30224b);color:#fff}.brand{display:flex;align-items:center;gap:6px;font-size:16px;font-weight:900;letter-spacing:.03em;white-space:nowrap}.bolt{color:var(--yellow);font-size:20px;line-height:1}.tag{overflow:hidden;color:#d7d8e0;font-size:11px;white-space:nowrap;text-overflow:ellipsis}
    main{padding:16px}.topline{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.eyebrow{font-size:14px;font-weight:750;color:var(--purple)}.score{color:var(--muted);font-size:14px;font-variant-numeric:tabular-nums}.progress{height:7px;margin-bottom:18px;overflow:hidden;border:1px solid var(--border);border-radius:999px;background:var(--panel-2)}.progress>span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--accent),#8d63e8);transition:width .25s ease}
    h1,h2,p{overflow-wrap:anywhere}h2{margin:0 0 16px;font-size:19px;line-height:1.35;letter-spacing:-.012em}.answers{display:grid;gap:9px}.answer{display:flex;align-items:flex-start;gap:10px;min-height:52px;padding:12px 13px;border:1px solid var(--border-strong);border-radius:var(--radius-control);background:var(--field);cursor:pointer;transition:border-color .15s ease,background-color .15s ease,box-shadow .18s ease}.answer:hover{border-color:var(--accent)}.answer:has(input:checked){border-color:var(--accent);background:color-mix(in srgb,var(--accent) 8%,var(--panel));box-shadow:0 0 0 2px color-mix(in srgb,var(--accent) 12%,transparent)}.answer:has(input:focus-visible){outline:2px solid var(--accent);outline-offset:2px;box-shadow:0 0 0 4px var(--focus)}.answer input{flex:0 0 auto;width:18px;height:18px;margin:1px 0 0;accent-color:var(--accent)}.answer span{min-width:0;line-height:1.4}
    .match-list{display:grid;gap:9px}.match{display:grid;grid-template-columns:minmax(0,1fr) minmax(132px,.75fr);gap:10px;align-items:center;padding:11px 12px;border:1px solid var(--border-strong);border-radius:var(--radius-control);background:var(--field)}.match select{width:100%;min-width:0;padding:9px 30px 9px 10px;border:1px solid var(--border-strong);border-radius:10px;background:var(--panel);color:var(--text)}.match select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
    .feedback{min-height:22px;margin-top:12px;font-size:14px;font-weight:750}.feedback.good{color:var(--success)}.feedback.bad{color:var(--danger)}.buttons{display:flex;gap:9px;margin-top:10px}button{min-height:44px;border:1px solid transparent;border-radius:var(--radius-control);padding:10px 15px;font-weight:750;cursor:pointer;transition:transform .12s ease,background-color .15s ease,filter .15s ease}button:active{transform:translateY(1px)}button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.primary{flex:1;background:var(--accent);color:#fff}.primary:hover{background:var(--accent-press)}.next{flex:1;background:var(--success);color:#fff}.secondary{background:var(--panel-2);border-color:var(--border-strong);color:var(--text)}.note{margin:13px 0 0;color:var(--muted);font-size:12px;line-height:1.4}
    .loading{padding:2px}.loading-card{position:relative;overflow:hidden;min-height:168px;padding:18px;border:1px solid color-mix(in srgb,var(--accent) 36%,var(--border));border-radius:14px;background:linear-gradient(180deg,color-mix(in srgb,var(--accent) 5%,var(--panel)),var(--panel));box-shadow:0 8px 22px rgba(25,31,45,.08)}.loading-head{display:flex;align-items:center;gap:12px}.loading-icon{position:relative;flex:0 0 auto;width:44px;height:44px;border:1px solid color-mix(in srgb,var(--purple) 38%,var(--border));border-radius:12px;background:linear-gradient(145deg,#30224b,#1d1d22);box-shadow:0 8px 18px rgba(26,20,42,.18)}.loading-icon::before{content:"⚡";position:absolute;inset:0;display:grid;place-items:center;color:var(--yellow);font-size:23px}.loading-copy{min-width:0}.loading-title{margin:0;font-size:18px;font-weight:800;line-height:1.25}.loading-message{margin:3px 0 0;color:var(--muted);font-size:14px}.loading-scan{height:8px;margin:20px 0 10px;overflow:hidden;border:1px solid var(--border);border-radius:999px;background:var(--panel-2)}.loading-scan span{display:block;width:42%;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--accent),var(--purple));animation:scan 1.45s ease-in-out infinite}.loading-meta{display:flex;align-items:center;justify-content:space-between;gap:10px;color:var(--muted);font-size:12px}.loading-step{white-space:nowrap}.loading-step::before{content:"";display:inline-block;width:7px;height:7px;margin-right:7px;border-radius:50%;background:var(--success);box-shadow:0 0 0 4px color-mix(in srgb,var(--success) 14%,transparent)}
    .error-card,.finish{padding:4px 2px}.error-card h1,.finish h1{margin:0 0 7px;font-size:22px;line-height:1.25}.error-card p,.finish p{margin:0;color:var(--muted)}.result-score{display:flex;align-items:baseline;gap:8px;margin-bottom:7px}.result-score strong{font-size:36px;line-height:1;color:var(--purple)}.result-score span{color:var(--muted);font-weight:650}.finish .buttons{margin-top:18px}.finish .secondary{width:100%}
    @keyframes scan{0%{transform:translateX(-115%)}50%{transform:translateX(72%)}100%{transform:translateX(245%)}}
    @media(prefers-color-scheme:dark){:root{--panel:#25262a;--panel-2:#2e3035;--field:#292b30;--text:#f2f4f8;--muted:#a8afbb;--border:#3b3e45;--border-strong:#484c55;--accent:#5b8ff9;--accent-press:#4b7fe8;--purple:#a16cff;--success:#2ecc71;--danger:#ff6f7c;--focus:rgba(91,143,249,.30);--shadow:0 9px 28px rgba(0,0,0,.25)}}
    @media(max-width:460px){body{padding:8px 10px 12px}.app{border-radius:15px}.brandbar{padding:10px 12px}main{padding:14px}.tag{max-width:150px}h2{font-size:18px;margin-bottom:14px}.answer{min-height:50px;padding:11px 12px}.match{grid-template-columns:1fr}.buttons{flex-direction:column}.buttons button{width:100%}.loading-card{min-height:158px;padding:16px}.loading-title{font-size:17px}}
    @media(max-width:370px){body{padding:7px 8px 10px}.brandbar{padding:9px 11px}.brand{font-size:15px}.tag{max-width:118px;font-size:10px}main{padding:12px}.topline{margin-bottom:8px}.eyebrow,.score{font-size:13px}h2{font-size:17px}.answer{gap:9px;padding:10px 11px}.loading-card{padding:14px}.loading-icon{width:40px;height:40px}.loading-meta{align-items:flex-start;flex-direction:column;gap:5px}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
  </style>
</head>
<body>
  <section class="app" aria-live="polite">
    <div class="brandbar"><div class="brand"><span>EZ</span><span class="bolt">⚡</span><span>QUIZ</span></div><div class="tag">Smart. Simple. Fast. EZ.</div></div>
    <main id="root"><div class="loading"><div class="loading-card"><div class="loading-head"><div class="loading-icon" aria-hidden="true"></div><div class="loading-copy"><p class="loading-title">Building your quiz...</p><p class="loading-message" id="loadingMessage">Preparing the question plan.</p></div></div><div class="loading-scan" aria-hidden="true"><span></span></div><div class="loading-meta"><span class="loading-step">Generation in progress</span><span id="loadingCount">Creating your questions</span></div></div></div></main>
  </section>
  <script>
    (()=>{
      const root=document.getElementById('root');let quiz=null,index=0,score=0,checked=false,nextRequestId=1,buildStarted=false,phaseTimer=null;const pendingRequests=new Map();
      const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
      const save=()=>window.openai?.setWidgetState?.({index,score,checked:false});
      function request(method,params){const id=nextRequestId++;window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');return new Promise((resolve,reject)=>pendingRequests.set(id,{resolve,reject}))}
      function currentOutput(){return window.openai?.toolOutput||null}
      function loadingMarkup(count){return '<div class="loading"><div class="loading-card"><div class="loading-head"><div class="loading-icon" aria-hidden="true"></div><div class="loading-copy"><p class="loading-title">Building your quiz...</p><p class="loading-message" id="loadingMessage">Preparing the question plan.</p></div></div><div class="loading-scan" aria-hidden="true"><span></span></div><div class="loading-meta"><span class="loading-step">Generation in progress</span><span id="loadingCount">Creating '+esc(count||10)+' questions</span></div></div></div>'}
      function showLoading(count){root.innerHTML=loadingMarkup(count);const phases=['Preparing the question plan.','Writing balanced questions.','Checking the quiz format.'];let phase=0;clearInterval(phaseTimer);phaseTimer=setInterval(()=>{phase=(phase+1)%phases.length;const el=document.getElementById('loadingMessage');if(el)el.textContent=phases[phase]},2300)}
      function showError(message){clearInterval(phaseTimer);root.innerHTML='<div class="error-card"><h1>Quiz generation stopped</h1><p>'+esc(message||'Please try again in a moment.')+'</p><div class="buttons"><button id="retry" class="primary">Try again</button></div></div>';const retry=root.querySelector('#retry');if(retry)retry.onclick=()=>startBuild(window.openai?.toolInput||{})}
      async function startBuild(input){if(buildStarted)return;buildStarted=true;const args=input&&typeof input==='object'?input:{};showLoading(args.count);try{const result=await request('tools/call',{name:'build_quiz',arguments:args});if(result?.isError)throw new Error(result.content?.[0]?.text||'EZ Quiz could not generate the quiz.');load(result)}catch(error){buildStarted=false;showError(error?.message)} }
      function load(value){const data=value?.structuredContent||value;if(data?.status==='loading'){startBuild(window.openai?.toolInput||value?._meta?.generateRequest||{});return}if(!data||!Array.isArray(data.questions)||!data.questions.length)return;clearInterval(phaseTimer);quiz=data;const prior=window.openai?.widgetState||{};index=Math.max(0,Math.min(data.questions.length-1,Number(prior.index)||0));score=Math.max(0,Number(prior.score)||0);checked=false;render()}
      function optionsFor(q){if(q.type==='MC')return q.options.map((o,i)=>'<label class="answer"><input type="'+(q.correct.length>1?'checkbox':'radio')+'" name="answer" value="'+i+'"><span>'+esc(o)+'</span></label>').join('');if(q.type==='TF'||q.type==='YN'){const labels=q.type==='TF'?['True','False']:['Yes','No'];return labels.map((o,i)=>'<label class="answer"><input type="radio" name="answer" value="'+(i===0?'true':'false')+'"><span>'+o+'</span></label>').join('')}if(q.type==='MT')return '<div class="match-list">'+q.left.map((left,i)=>'<label class="match"><span>'+(i+1)+'. '+esc(left)+'</span><select data-left="'+i+'"><option value="">Choose a match</option>'+q.right.map((right,j)=>'<option value="'+j+'">'+String.fromCharCode(65+j)+'. '+esc(right)+'</option>').join('')+'</select></label>').join('')+'</div>';return ''}
      function isCorrect(q){if(q.type==='MC'){const chosen=[...root.querySelectorAll('input[name=answer]:checked')].map(el=>Number(el.value)).sort((a,b)=>a-b);return JSON.stringify(chosen)===JSON.stringify([...q.correct].sort((a,b)=>a-b))}if(q.type==='TF'||q.type==='YN'){const picked=root.querySelector('input[name=answer]:checked');return !!picked&&String(q.correct)===picked.value}if(q.type==='MT'){const chosen=[...root.querySelectorAll('select[data-left]')].map(el=>[Number(el.dataset.left),Number(el.value)]);return chosen.length===q.matches.length&&q.matches.every(([a,b])=>chosen.some(([x,y])=>x===a&&y===b))}return false}
      function answerText(q){if(q.type==='MC')return q.correct.map(i=>q.options[i]).join(', ');if(q.type==='TF')return q.correct?'True':'False';if(q.type==='YN')return q.correct?'Yes':'No';if(q.type==='MT')return q.matches.map(([a,b])=>(a+1)+'-'+String.fromCharCode(65+b)).join(', ');return ''}
      function render(){if(!quiz)return;const q=quiz.questions[index];const pct=Math.round(((index+1)/quiz.questions.length)*100);root.innerHTML='<div class="topline"><span class="eyebrow">Question '+(index+1)+' of '+quiz.questions.length+'</span><span class="score">Score: '+score+'</span></div><div class="progress" aria-label="Quiz progress"><span style="width:'+pct+'%"></span></div><h2>'+esc(q.prompt)+'</h2><div class="answers">'+optionsFor(q)+'</div><div id="feedback" class="feedback" role="status"></div><div class="buttons"><button id="check" class="primary">Check answer</button><button id="next" class="next" hidden>'+(index+1===quiz.questions.length?'See results':'Next question')+'</button></div><p class="note">'+(quiz.aiGenerated?'AI-generated quiz. Check important facts against your source.':'Quiz content supplied by the user.')+'</p>';root.querySelector('#check').onclick=()=>{if(checked)return;const ok=isCorrect(q);checked=true;if(ok)score++;const feedback=root.querySelector('#feedback');feedback.className='feedback '+(ok?'good':'bad');feedback.textContent=ok?'Correct!':'Not quite. Correct answer: '+answerText(q);root.querySelectorAll('input,select').forEach(el=>el.disabled=true);root.querySelector('#check').hidden=true;root.querySelector('#next').hidden=false};root.querySelector('#next').onclick=()=>{if(index+1>=quiz.questions.length){finish();return}index++;checked=false;save();render()}}
      function finish(){save();const total=quiz.questions.length;const message=score===total?'Perfect score.':score>=Math.ceil(total*.7)?'Nice work.':'Review the misses and try again.';root.innerHTML='<div class="finish"><div class="result-score"><strong>'+score+'</strong><span>out of '+total+'</span></div><h1>Quiz complete</h1><p>'+message+'</p><div class="buttons"><button id="restart" class="secondary">Try again</button></div><p class="note">'+esc(quiz.title||'EZ Quiz')+'</p></div>';root.querySelector('#restart').onclick=()=>{index=0;score=0;checked=false;save();render()}}
      window.addEventListener('message',event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=='2.0')return;if(message.id!==undefined&&pendingRequests.has(message.id)){const pending=pendingRequests.get(message.id);pendingRequests.delete(message.id);if(message.error)pending.reject(message.error);else pending.resolve(message.result);return}if(message.method==='ui/notifications/tool-input'&&message.params?.arguments&&!buildStarted)startBuild(message.params.arguments);if(message.method==='ui/notifications/tool-result')load(message.params)});
      const initial=currentOutput();if(initial)load(initial);else showLoading(window.openai?.toolInput?.count);
      request('ui/initialize',{protocolVersion:'2025-11-21',appInfo:{name:'ez-quiz-player',title:'EZ Quiz',version:'2.0.0',websiteUrl:'https://ez-quiz.app'},appCapabilities:{}}).then(result=>{window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized'},'*');if(!buildStarted&&result?.toolInput)startBuild(result.toolInput)}).catch(()=>{});
    })();
  </script>
</body>
</html>`;
}

module.exports = { QUIZ_WIDGET_MIME_TYPE, QUIZ_WIDGET_URI, quizWidgetHtml };
