name: Dependency Review

on:
  pull_request:
    branches: [ "main", "beta" ]

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@45529485b5eb76184ced07362d2331fd9d26f03f # v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: true

