name: Security Scorecards

on:
  schedule:
    - cron: '34 2 * * 1'
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      actions: read
      contents: read
      issues: read
      pull-requests: read
      security-events: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true

      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v3
        with:
          sarif_file: results.sarif

