name: Security Scorecards

on:
  schedule:
    - cron: '34 2 * * 1'
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534 # v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true

      - name: Upload Scorecard results to code scanning
        uses: github/codeql-action/upload-sarif@5d5cd550d3e189c569da8f16ea8de2d821c9bf7a # v3
        with:
          sarif_file: results.sarif

